version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: password_to_be_defined
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: email_to_be_defined
      PGADMIN_DEFAULT_PASSWORD: password_to_be_defined
    ports:
      - "80:80"